version: "3.9"

services:
  pimatic:
    build: .
    ports:
      - "8080:80"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ${PWD}/config.json:/etc/opt/pimatic-app/config.json
