#! /bin/sh
### BEGIN INIT INFO
# Provides:          pimatic
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: pimatic service
# Description:       pimatic home automation framework init.d script for debian systems.
### END INIT INFO

if [ "$1" = "start" ] || [ "$1" = "stop" ] || [ "$1" = "restart" ] || [ "$1" = "status" ]
then
	/etc/opt/pimatic-app/node_modules/pimatic/pimatic.js $1
	exit "$?"
else
	echo "Usage: service pimatic {start|stop|status|restart}" >&2
	exit 3
fi
